name : "CD Pipeline" # name of the workflow/pipeline

on: # event that triggers the workflow
  workflow_run: # once our ci pipeline is completed then trigger this cd pipeline
    workflows: ["sample react pipelie/workflow"]
    types:
        - completed
    workflow_dispatch: # manual ui trigger

jobs:
  deploy: # job name
      runs-on: ubuntu-latest # runner os
      environment: production # environment name  

      steps:

        - name: "Setup Nodejs" # nodejs setup step
          uses: actions/setup-node@v6
          with:
            node-version: '24'

        - name: "Setup vercel cli"
          run: npm install -g vercel # linux command to install vercel cli


        - name : "download build file" # download build artifact step
          uses : actions/download-artifact@v4
          with:
            name: build # artifact name to be downloaded
            run-id: ${{ github.event.workflow_run.id }}
            github-token: ${{ github.token }}

        - name: "deploy to vercel"
          run: vercel --prod --token ${{ secrets.VERCEL_TOKEN }} --confirm --name=cicdpipeline-project