name : "sample react pipelie/workflow"
on:
  push:
    branches:
      - master
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps: 
        - name: "Setup Nodejs"
          uses: actions/setup-node@v6 # setup node js env on the new linux machine provided by github
          with:
            node-version: '24'

        - name: "check node version"
          run: node --version

        - name: "clone the repository"
          uses: actions/checkout@v2 # fetch repositoy inside the runner machine(ubuntu)

        - name: "list directories"
          run: ls

        - name: "install dependencies"
          run: npm install

        - name : "list directories"
          run : ls

        - name: "run lint"
          run: npm run lint

        - name: "run tests"
          run: npm test

        - name: "build project"
          run: npm run build