name : "sample react pipelie/workflow"
on:
  push:
    branches:
      - master
      - main

jobs:
  build-and-test:
    - runs-on: ubuntu-latest

    steps: 
      - name: "Setup Nodejs"
        uses: actions/setup-node@v6
        with:
          node-version: '24'

    - name         